version: 2
jobs:
  build:
    working_directory: ~/querycert/qcert
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - run: export DEBIAN_FRONTEND=noninteractive && sudo apt-get remove -y --purge mysql-server mysql-community-server
    - restore_cache:
        keys:
        - v2-dep-{{ .Branch }}-
        - v2-dep-master-
        - v2-dep-
    - run: sudo add-apt-repository -y ppa:avsm/ppa
    - run: sudo apt-get -qq update
    - run: sudo apt-get install -y ocaml-nox ocaml-native-compilers opam
    - run: export TERM=dumb && opam init -a
    - run: export TERM=dumb && opam switch 4.06.1
    - run: eval `opam config env`
    - run: export TERM=dumb && opam repo add coq-released https://coq.inria.fr/opam/released || true
    - run: export TERM=dumb && opam update || true
    - run:
        command: export TERM=dumb && opam install -y ocamlbuild menhir camlp5 base64 js_of_ocaml js_of_ocaml-ppx coq.8.8.1
        no_output_timeout: 1200s
    - run: export TERM=dumb && opam install -y coq-flocq coq-jsast
    - save_cache:
        key: v2-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.opam
    - run: eval `opam config env` && make -j2
    - run: make tests
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
