version: 2
jobs:
  build:
    working_directory: ~/querycert/qcert
    parallelism: 1
    shell: /bin/bash --login
    environment:
      PATH: ~/qcert/bin/:~/spark-2.1.2-bin-hadoop2.7/bin/:$PATH
    docker:
    - image: circleci/node:8
      command: /sbin/init
    steps:
    - checkout
    - run:
        working_directory: ~/querycert/qcert
        command: export DEBIAN_FRONTEND=noninteractive && sudo apt-get remove -y --purge mysql-server mysql-community-server
    - run:
        working_directory: ~/querycert/qcert
        command: echo -e "export PATH=~/qcert/bin/:~/spark-2.1.2-bin-hadoop2.7/bin/:$PATH" >> $BASH_ENV
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: sudo add-apt-repository -y ppa:avsm/ppa
    - run: sudo apt-get -qq update
    - run: sudo apt-get install -y ocaml-nox ocaml-native-compilers opam
    - run: opam init -a
    - run: opam switch 4.05.0
    - run: eval `opam config env`
    - run:
        command: opam install -y ocamlbuild menhir camlp5 base64 js_of_ocaml js_of_ocaml-ppx coq.8.7.1
        no_output_timeout: 1200s
    - run: if [[ ! -d ~/spark-2.1.2-bin-hadoop2.7 ]]; then cd ~/ && wget http://www.mirrorservice.org/sites/ftp.apache.org/spark/spark-2.1.2/spark-2.1.2-bin-hadoop2.7.tgz && tar xf spark-2.1.2-bin-hadoop2.7.tgz ; fi
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.opam
        - ~/spark-2.1.2-bin-hadoop2.7
    - run: eval `opam config env` && make SPARK=yes
    - run: make tests
    - run: cd samples/spark2 && ./run.sh
    - store_artifacts:
        path: samples/spark2/test01_nnrc/irs
    - store_artifacts:
        path: samples/spark2/test01_nnrcmr/irs
